# Generated by Django 4.2.1 on 2023-06-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
