# Generated by Django 4.2.1 on 2023-06-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_userlog_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
